language: csharp
solution: Heroko.sln
script:
  - xbuild /p:VbcToolExe=vbnc.exe Heroko.sln
deploy:
  provider: heroku
  api_key:
    secure: f3a68f64-4b62-401c-a6a6-07fdab72870e
  app: Heroku
  on:
    repo: easfilho/Heroku
notifications:
  email:
    recipients:
        - allanmleite@hotmail.com
