language: csharp
solution: "Heroko.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" Heroko.sln
script:
- xbuild Heroko.sln
- mono ./Heroko.Tests/bin/Debug/Heroko.Tests.dll



language: csharp
solution: Heroko.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore Herolo.sln

script:
  - xbuild Heroko
  - nunit-console ./Heroko.Tests/bin/Debug/Heroko.Tests.dll
